language: objective-c
xcode_project: StoryboardXibControllerDemo/StoryboardXibControllerDemo.xcodeproj
xcode_scheme: StoryboardXibControllerDemo
before_install: gem install cocoapods
xcode_sdk: iphonesimulator
script: xctool -project StoryboardXibControllerDemo/StoryboardXibControllerDemo.xcodeproj -scheme StoryboardXibControllerDemo -sdk iphonesimulator build